### ISSUE TITLE
Just enough to support Sidekiq

### ISSUE THREAD

**Issue by munckymagik** [munckymagik/redis-clone#1]
List generated by grepping the Sidekiq source code. These are the commands that need to be supported:

* keyspace:
  - [x] [KEYS](https://redis.io/commands/keys) (not actually used in Sidekiq but needed to humans and tests)
  - [x] [DEL](https://redis.io/commands/del)
  - [x] [TYPE](https://redis.io/commands/type)
  - [x] [EXPIRE](https://redis.io/commands/expire)
  - [x] [EXISTS](https://redis.io/commands/exists)
* strings:
  - [x] [GET](https://redis.io/commands/get)
  - [x] [INCR](https://redis.io/commands/incr)
  - [x] [INCRBY](https://redis.io/commands/incrby)
  - [x] [SET](https://redis.io/commands/set) (exists but need to support key expiry)
  - [x] [MGET](https://redis.io/commands/mget)
  - [x] [MSET](https://redis.io/commands/mset)
* lists:
  - [x] [LLEN](https://redis.io/commands/llen)
  - [x] [LPUSH](https://redis.io/commands/lpush)
  - [x] [LRANGE](https://redis.io/commands/lrange)
  - [x] [LREM](https://redis.io/commands/lrem)
  - [x] [RPOP](https://redis.io/commands/rpop)
  - [x] [RPUSH](https://redis.io/commands/rpush)
  - [ ] [BRPOP](https://redis.io/commands/brpop)
* hash:
  - [x] [HSET](https://redis.io/commands/hset)
  - [x] [HGET](https://redis.io/commands/hget)
  - [x] [HMSET](https://redis.io/commands/hmset)
  - [x] [HMGET](https://redis.io/commands/hmget)
  - [x] [HGETALL](https://redis.io/commands/hgetall)
* sets:
  - [ ] [SADD](https://redis.io/commands/sadd)
  - [ ] [SCARD](https://redis.io/commands/scard)
  - [ ] [SMEMBERS](https://redis.io/commands/smembers)
  - [ ] [SREM](https://redis.io/commands/srem)
  - [ ] [SSCAN](https://redis.io/commands/sscan) (Ruby [sscan_each](https://www.rubydoc.info/github/redis/redis-rb/Redis:sscan_each))
* sorted sets:
  - [ ] [ZADD](https://redis.io/commands/zadd)
  - [ ] [ZCARD](https://redis.io/commands/zcard)
  - [ ] [ZINCRBY](https://redis.io/commands/zincrby)
  - [ ] [ZRANGE](https://redis.io/commands/zrange)
  - [ ] [ZRANGEBYSCORE](https://redis.io/commands/zrangebyscore)
  - [ ] [ZREM](https://redis.io/commands/zrem)
  - [ ] [ZREMRANGEBYRANK](https://redis.io/commands/zremrangebyrank)
  - [ ] [ZREMRANGEBYSCORE](https://redis.io/commands/zremrangebyscore)
  - [ ] [ZREVRANGE](https://redis.io/commands/zrevrange)
  - [ ] [ZSCAN](https://redis.io/commands/zscan) (Ruby [zscan_each](https://www.rubydoc.info/github/redis/redis-rb/Redis:zscan_each))
* connection:
  - [ ] [CONNECTION](https://redis.io/commands/connection)
  - [ ] [DISCONNECT](https://redis.io/commands/disconnect)
* server:
  - [ ] [INFO](https://redis.io/commands/info)
* transactions:
  - [ ] [MULTI](https://redis.io/commands/multi)
